image: maven:3.6.3

pipelines:
  default:
      
      - step:
          name: Build and Push Images
          script:
            - docker build -t vyasg84/springboot:latest .
            - docker push vyasg84/springboot:latest
          services:
            - docker
      -  step:
           name: Deployment 
           script:
            - pipe: atlassian/ssh-run:0.4.1
              variables:
                SSH_USER: 'root'
                SERVER: '165.22.208.179'
                
                # SSH_KEY: $SSH_KEY
                
                COMMAND: >
                  rm -rf springboot-test/* &&
                  git clone https://vyasgaurav@bitbucket.org/vyasgaurav/springboot-test.git &&
                  cd springboot-test &&
                  docker-compose up -d
